/**:
  ros__parameters:
    map_frame: map
    utm_zone: 52
    origin_easting_m: 330344.301121512195095
    origin_northing_m: 4156712.793599965050817
    origin_altitude_m: 0.0
    origin_source_csv: gongD_back.csv
    min_position_variance_m2: 0.0001
